sudo: false
language: scala
script: sbt +test
jdk: openjdk8
matrix:
  include:
    - env: PLAY_VERSION=2.6
    - env: PLAY_VERSION=2.7
cache:
  directories:
    - '$HOME/.ivy2/cache'
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
branches:
  except:
    - master
